#!/usr/bin/env python3
"""Smoke test for `dnafeaturesviewer_genbank_plot`: Parse examples/example_sequence.gb via BiopythonTranslator().translate_record, plot, and save PNG; assert >=10 features and a valid non-empty PNG.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "ghcr.io/doctordean/lazarus-dnafeaturesviewer:genbank-plot-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && python run_genbank_plot.py examples/example_sequence.gb /tmp/smoke 2>/dev/null | grep -oP 'feature_count=\\K[0-9]+' | awk '{print \"feature_count=\"$1}'"
METRIC = "feature_count"
THRESHOLD = 10


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
