#!/usr/bin/env python3
"""Call `basset_predict` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/basset:site-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "set -euo pipefail\nsource /etc/profile.d/basset.sh\ncd \"$BASSETDIR\"\nmkdir -p \"$OUTDIR\"\n# 1) Encode input FASTA -> HDF5 (test_in). The encoder now uppercases soft-masked\n#    (lowercase) bases and centers/trims each sequence to the model's 600 bp window.\npython src/fasta_to_h5.py \"$INPUT\" \"$OUTDIR/seqs.h5\"\n# 2) Run the pretrained Basset ConvNet forward pass on CPU.\nth src/basset_predict.lua data/models/pretrained_model.th \"$OUTDIR/seqs.h5\" \"$OUTDIR/predictions.txt\"\necho \"Wrote $OUTDIR/predictions.txt : one row per input sequence, 164 tab-separated\"\necho \"DNaseI-hypersensitivity / chromatin-accessibility probabilities (ENCODE+Roadmap cell types).\""


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
