#!/usr/bin/env python3
"""Smoke test for `basset_predict`: Encode 4 real (soft-masked) genomic sequences and run the forward pass; assert the 164-column probability matrix has non-degenerate variance across cell types (min per-sequence std over the 164 targets).

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/basset:site-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "source /etc/profile.d/basset.sh && cd $BASSETDIR && awk '/^>/{c++} c<=4{print} c>4{exit}' data/encode_roadmap.fa > /tmp/smoke.fa && python src/fasta_to_h5.py /tmp/smoke.fa /tmp/smoke.h5 2>/dev/null && th src/basset_predict.lua data/models/pretrained_model.th /tmp/smoke.h5 /tmp/smoke.txt 2>/dev/null && python -c \"import numpy as np; P=np.loadtxt('/tmp/smoke.txt'); assert P.shape[1]==164 and P.min()>=0 and P.max()<=1; print('min_perseq_std=%.4f'%P.std(1).min())\""
METRIC = "min_perseq_std"
THRESHOLD = 0.01


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
