#!/usr/bin/env python3
"""Call `sequoya_nsgaii_msa` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/sequoya:nsgaii-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "set -euo pipefail\ncd /root/repo\n\n# INPUT is a BAliBASE .tfa file, e.g. resources/bb3_release/RV11/BB11001.tfa\n# The BAliBASE loader needs the resources ROOT (the dir that contains both\n# bb3_release/ and bb3_aligned/), plus the instance name (basename minus .tfa).\nINPUT=\"${INPUT:-}\"\nOUTDIR=\"${OUTDIR:-/tmp/out}\"\nMAX_EVALUATIONS=\"${MAX_EVALUATIONS:-3000}\"\nmkdir -p \"$OUTDIR\"\n\nif [ -n \"$INPUT\" ] && [ -f \"$INPUT\" ]; then\n  INSTANCE=\"$(basename \"$INPUT\" .tfa)\"\n  # .../resources/bb3_release/RV11/BB11001.tfa  -> resources root is three dirs up\n  RESROOT=\"$(cd \"$(dirname \"$INPUT\")/../..\" && pwd)\"\nelse\n  # Fall back to the shipped BB11001 instance baked into the image.\n  INSTANCE=\"BB11001\"\n  RESROOT=\"/root/repo/resources\"\nfi\n\necho \"Running NSGA-II MSA optimization: instance=$INSTANCE resources=$RESROOT max_evaluations=$MAX_EVALUATIONS\"\npython /root/repo/examples/nsgaii_bb11001.py \"$INSTANCE\" \"$RESROOT\" \"$MAX_EVALUATIONS\" \\\n  2> \"$OUTDIR/${INSTANCE}_run.log\" \\\n  | tee \"$OUTDIR/${INSTANCE}_pareto_front.txt\""


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
