#!/usr/bin/env python3
"""Smoke test for `sequoya_nsgaii_msa`: Run non-distributed NSGA-II (pop=100, offspring=100, SPXMSA crossover, ShiftClosedGapGroups mutation, 3000 evaluations) on the shipped BB11001 and confirm the final Pareto front is non-empty and its best SumOfPairs did not degrade vs the initial precomputed-alignment population.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/sequoya:nsgaii-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && python examples/nsgaii_bb11001.py BB11001 resources 3000 2>/dev/null | grep sum_of_pairs_delta_vs_initial"
METRIC = "sum_of_pairs_delta_vs_initial"
THRESHOLD = 0


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
