#!/usr/bin/env python3
"""Call `diffdock_blind_docking` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "ghcr.io/doctordean/lazarus-diffdock:site-ready"
PLATFORM = "linux/amd64"
GPUS = "all"  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "set -euo pipefail\ncd /home/appuser/DiffDock\n# INPUT: a DiffDock CSV (columns: complex_name,protein_path,ligand_description,protein_sequence).\n#   protein_path = path to a receptor PDB; ligand_description = a SMILES string OR a path to an SDF/MOL2 ligand.\n#   (Blind docking: DiffDock randomizes the ligand position, so no binding site is required.)\n# OUTPUT: $OUTDIR/<complex_name>/rank1.sdf ... rankN.sdf  plus rankK_confidence<score>.sdf (ranked by confidence).\nmkdir -p \"$OUTDIR\"\n/home/appuser/bin/micromamba run -n diffdock python inference.py \\\n  --config default_inference_args.yaml \\\n  --protein_ligand_csv \"$INPUT\" \\\n  --out_dir \"$OUTDIR\" \\\n  --model_dir ./workdir/v1.1/score_model \\\n  --confidence_model_dir ./workdir/v1.1/confidence_model \\\n  --samples_per_complex 10\necho \"Ranked poses written to $OUTDIR/<complex_name>/rank1.sdf .. rank10.sdf (confidence in rankK_confidence*.sdf filenames)\""


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
