#!/usr/bin/env python3
"""Smoke test for `despasito_saft_gamma_mie_propane_saturation`: Run the propane SAFT-gamma Mie saturation calculation and compare computed vapor pressures to the shipped experimental curve; passes if AARD < 0.15 and all non-trivial points are finite.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/despasito:propane-sat-working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "source activate despasito && cd /root/repo/despasito/examples/saft_gamma_mie/pure_component && python lazarus_smoke.py"
METRIC = "aard_vapor_pressure"
THRESHOLD = 0.15


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
