#!/usr/bin/env python3
"""Smoke test for `pyamg_ruge_stuben_solve`: Build A=poisson((500,500),'csr'), random b, ruge_stuben_solver, solve tol=1e-10; assert relative residual ||b-A@x||/||b|| < 1e-8

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/pyamg:solve-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "python3 /root/solve_poisson.py '' /tmp/smoke && python3 -c \"import json;m=json.load(open('/tmp/smoke/metrics.json'));print('relative_residual=%.3e'%m['relative_residual']);assert m['relative_residual']<1e-8\""
METRIC = "relative_residual"
THRESHOLD = 1e-08


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
