#!/usr/bin/env python3
"""Call `scannet_ppi_binding_sites` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/scannet:ppi-noMSA-proven"
PLATFORM = "linux/amd64"
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "set -e\ncd /ScanNet\nCHAIN=\"${CHAIN:-A}\"\nBASE=$(basename \"$INPUT\")\nBASE=\"${BASE%.*}\"\nNAME=\"${BASE}_${CHAIN}\"\nmkdir -p \"$OUTDIR\"\n# ScanNet chain syntax: <path/to/file.pdb>_<CHAIN>. Structure-only mode (--noMSA), single chain (--pdb).\npython predict_bindingsites.py \"${INPUT}_${CHAIN}\" --mode interface --noMSA --pdb --name \"$NAME\" --predictions_folder \"$OUTDIR/\"\n# Surface the per-residue CSV at a stable top-level path.\ncp \"$OUTDIR/${NAME}_(0-${CHAIN})_single_ScanNet_interface_noMSA/predictions_${NAME}.csv\" \"$OUTDIR/predictions_${NAME}.csv\"\necho \"Per-residue binding-site probabilities: $OUTDIR/predictions_${NAME}.csv\""


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    _run("docker", "run", "-d", "--name", name, "--platform", PLATFORM,
         IMAGE, "sleep", "infinity")
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
