#!/usr/bin/env python3
"""Smoke test for `scannet_ppi_binding_sites`: Fetch full 4ZQK complex, derive PD-L1 (chain A) interface residues as chain-A residues with any heavy atom within 5.0 A of partner chain PD-1 (Biopython), compute ROC-AUC of ScanNet per-residue probabilities vs those labels. Must be >= 0.70.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "ghcr.io/doctordean/lazarus-scannet:ppi-noMSA-proven"
PLATFORM = "linux/amd64"
COMMAND = "cd /ScanNet && CHAIN=A INPUT=/ScanNet/PDB/4zqk.pdb OUTDIR=/ScanNet/predictions bash -c 'python predict_bindingsites.py \"${INPUT}_${CHAIN}\" --mode interface --noMSA --pdb --name 4ZQK_A --predictions_folder /ScanNet/predictions/' >/dev/null 2>&1; python sanity_check.py 2>/dev/null | grep ROC_AUC"
METRIC = "ROC_AUC"
THRESHOLD = 0.7


def main() -> int:
    proc = subprocess.run(
        ["docker", "run", "--rm", "--platform", PLATFORM, IMAGE, "bash", "-lc", COMMAND],
        capture_output=True, text=True,
    )
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
