#!/usr/bin/env python3
"""Smoke test for `dmasif_site`: Run dMaSIF-site on 4ZQK chain A, map per-point scores to residues (nearest atom, max-aggregate), and compute residue-level ROC-AUC against the true PD-L1 interface (chain A heavy atoms within 5.0A of partner chain B). Must exceed 0.65.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/dmasif:site-ready"
PLATFORM = "linux/amd64"
GPUS = "all"  # e.g. "all" to pass GPUs, or None
COMMAND = "export KEOPS_CACHE_FOLDER=/root/keops_cache; cd /root/MaSIF_colab && python predict_site.py examples/4ZQK.pdb /tmp/smoke A cuda:0 >/dev/null 2>&1 && python smoke_test.py examples/4ZQK.pdb /tmp/smoke A B 2>/dev/null | grep ROCAUC"
METRIC = "ROCAUC"
THRESHOLD = 0.65


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
