#!/usr/bin/env python3
"""Call `equidock_rigid_docking` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/equidock:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "set -e\nsource activate equidock\nexport DGLBACKEND=pytorch\ncd /root/repo\n\n# Derive the DB5 target id from the input ligand PDB filename (e.g. 1AVX_l_b.pdb -> 1AVX)\nBASE=$(basename \"$INPUT\")\nTARGET=${BASE%_l_b.pdb}\n\n# Stage the provided (randomly rotated/translated) unbound ligand into the DB5 test input dir.\n# The matching receptor / ground-truth complex must exist in\n# test_sets_pdb/db5_test_random_transformed/complexes/ (shipped for DB5 targets).\ncp \"$INPUT\" test_sets_pdb/db5_test_random_transformed/random_transformed/\"$BASE\"\n\n# create_dir() refuses to overwrite an existing results dir, so clear it first.\nrm -rf test_sets_pdb/db5_equidock_results\n\n# Predict the rigid docking pose for this single target (CPU, dataset=db5, remove_clashes=False).\nEQUIDOCK_TARGET=\"$TARGET\" python -m src.inference_rigid\n\n# Publish the transformed (docked) ligand PDB.\nmkdir -p \"$OUTDIR\"\ncp test_sets_pdb/db5_equidock_results/\"${TARGET}\"_l_b_EQUIDOCK.pdb \"$OUTDIR\"/\necho \"Docked ligand pose written to $OUTDIR/${TARGET}_l_b_EQUIDOCK.pdb\""


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
