#!/usr/bin/env python3
"""Smoke test for `equidock_rigid_docking`: Regenerate 1AVX docked ligand pose (db5, remove_clashes=False) and compute CA-atom RMSD (no re-alignment) vs the repo's shipped reference output. Must be < 2.0 A (ideally ~0), proving model+weights+graph pipeline reproduce the authors' published pose.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/equidock:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && source activate equidock && export DGLBACKEND=pytorch && rm -rf test_sets_pdb/db5_equidock_results && EQUIDOCK_TARGET=1AVX python -m src.inference_rigid >/dev/null 2>&1 && python /root/ca_rmsd.py test_sets_pdb/db5_equidock_results/1AVX_l_b_EQUIDOCK.pdb /root/db5_equidock_results_REFERENCE/1AVX_l_b_EQUIDOCK.pdb 2>/dev/null | grep ligand_CA_RMSD"
METRIC = "ligand_CA_RMSD_vs_reference_output"
THRESHOLD = 2


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
