#!/usr/bin/env python3
"""Smoke test for `deeplatentmicrobiome_env2otu`: Reproduce the test split (random_state=42), predict OTU composition from the 3 env features via encoder_domain->decoder, and report the mean per-sample Pearson correlation vs TSS-normalized observed OTUs.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "ghcr.io/doctordean/lazarus-dlm:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo/Src && python lazarus_infer.py 2>/dev/null | grep pearson_r"
METRIC = "pearson_r"
THRESHOLD = 0.65


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
