#!/usr/bin/env python3
"""Smoke test for `matador_kp_convex_hull`: Rebuild the binary K-P convex hull from the 295 shipped .res files and compare computed hull_dist to the shipped reference tests/data/test_KP_hull_dist.dat (mirrors test_binary_hull_distances).

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/matador:hull-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && python run_hull.py tests/data/hull-KP-KSnP_pub /tmp/smoke_out K,P 2>/dev/null | grep hull_dist_max_abs_error_vs_reference"
METRIC = "hull_dist_max_abs_error_vs_reference"
THRESHOLD = 0.001


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
