#!/usr/bin/env python3
"""Smoke test for `equibind_blind_docking`: Download PDB 6MOA, blind-dock the JW4 ligand with the pretrained flexible_self_docking checkpoint, and verify the predicted ligand heavy-atom centroid is within 10 A of the crystal ligand centroid (proves the true binding pocket was found, not a floating/NaN pose).

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/equibind:contract-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "bash /root/repo/lazarus_smoke.sh"
METRIC = "ligand_centroid_distance_A"
THRESHOLD = 10


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
