#!/usr/bin/env python3
"""Smoke test for `ahg_estimate`: Run ahg_estimate on the shipped nwis dataset; assert top row viable and mass-conserving (exponents sum to 1 within 0.05).

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/ahgestimation:ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "Rscript /usr/local/bin/run_ahg.R nwis /tmp/ahgout >/tmp/ahg.log 2>&1; grep continuity_abs_error /tmp/ahg.log | sed 's/continuity_abs_error=/continuity_exponent_sum_error=/'"
METRIC = "continuity_exponent_sum_error"
THRESHOLD = 0.05


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
