#!/usr/bin/env python3
"""Smoke test for `deepfri_mf`: Predict MF-GO terms for Parvalbumin alpha (PDB 1S3P chain A) and check the top term is GO:0005509 (calcium ion binding) with high confidence.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/deepfri:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && rm -rf /tmp/smoke_out && mkdir -p /tmp/smoke_out && python predict.py --cmap ./examples/pdb_cmaps/1S3P-A.npz -ont mf -o /tmp/smoke_out/DeepFRI >/dev/null 2>&1 && python3 -c \"import csv; rows=[r for r in csv.reader(open('/tmp/smoke_out/DeepFRI_MF_predictions.csv')) if r and not r[0].startswith('###') and r[0]!='Protein']; top=rows[0]; print('top1_go_term_and_score=%s' % (top[2] if top[1]=='GO:0005509' else '0'))\""
METRIC = "top1_go_term_and_score"
THRESHOLD = 0.9


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
