#!/usr/bin/env python3
"""Call `w2w_lcz_to_wrf` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/w2w:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "#!/usr/bin/env bash\nset -euo pipefail\n\n# $INPUT  : a directory containing the WRF geo_em.d01..d04.nc domain files\n#           and the WUDAPT LCZ GeoTIFF.\n# $OUTDIR : where the three modified WRF NetCDF files are written.\n#\n# Override the LCZ tif / WRF file names via env if they differ from the\n# shipped Zaragoza sample defaults.\nLCZ_FILE=\"${LCZ_FILE:-lcz_zaragoza.tif}\"\nWRF_FILE=\"${WRF_FILE:-geo_em.d04.nc}\"\n\nmkdir -p \"$OUTDIR\"\nIODIR=\"$OUTDIR/io\"\nrm -rf \"$IODIR\"\nmkdir -p \"$IODIR\"\n\n# Stage inputs into a writable working dir (w2w writes outputs alongside inputs).\ncp \"$INPUT\"/*.nc  \"$IODIR\"/ 2>/dev/null || true\ncp \"$INPUT\"/*.tif \"$IODIR\"/ 2>/dev/null || true\n\n# Run the WUDAPT-to-WRF inference (needs d01-d04 present for nesting hierarchy).\nw2w \"$IODIR\" \"$LCZ_FILE\" \"$WRF_FILE\"\n\n# Surface the three headline outputs into $OUTDIR.\nbase=\"${WRF_FILE%.nc}\"\ncp \"$IODIR/${base}_NoUrban.nc\"    \"$OUTDIR\"/\ncp \"$IODIR/${base}_LCZ_extent.nc\" \"$OUTDIR\"/\ncp \"$IODIR/${base}_LCZ_params.nc\" \"$OUTDIR\"/\n\necho \"Outputs written to $OUTDIR:\"\nls -la \"$OUTDIR\"/${base}_NoUrban.nc \"$OUTDIR\"/${base}_LCZ_extent.nc \"$OUTDIR\"/${base}_LCZ_params.nc"


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
