#!/usr/bin/env python3
"""Smoke test for `w2w_lcz_to_wrf`: Run w2w on the shipped Zaragoza sample and compare generated FRC_URB2D against the committed reference geo_em.d04_LCZ_params.nc.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/w2w:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "mkdir -p /root/smoke && cp /root/repo/sample_data/geo_em.d0[1-4].nc /root/repo/sample_data/lcz_zaragoza.tif /root/smoke/ && w2w /root/smoke lcz_zaragoza.tif geo_em.d04.nc >/dev/null 2>&1 && python3 -c \"import numpy as np,xarray as xr; g=xr.open_dataset('/root/smoke/geo_em.d04_LCZ_params.nc')['FRC_URB2D'].values.astype('f8'); r=xr.open_dataset('/root/repo/sample_data/geo_em.d04_LCZ_params.nc')['FRC_URB2D'].values.astype('f8'); print('max_abs_diff_FRC_URB2D=%.3e'%float(np.max(np.abs(g-r))))\""
METRIC = "max_abs_diff_FRC_URB2D"
THRESHOLD = 0.0001


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
