#!/usr/bin/env python3
"""Call `masif_site` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Usage:
    python predict.py <input> <output_dir>
"""
import subprocess
import sys
from pathlib import Path

IMAGE = "lazarus/masif:site-ready"
PLATFORM = "linux/amd64"
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "#!/bin/bash\nset -euo pipefail\n\n# MaSIF-site inference on a single PDB structure.\n# INPUT: a .pdb file.  OUTDIR: where per-vertex scores + colored surface land.\n# The target chain defaults to \"A\"; override with env MASIF_CHAIN.\n# PPI_PAIR_ID is <PDBID>_<CHAIN> (single chain => MaSIF-site inference on that chain).\n\nCHAIN=\"${MASIF_CHAIN:-A}\"\n# PDB id = uppercased input basename without extension\nPDB_ID=$(basename \"$INPUT\" | sed 's/\\.[^.]*$//' | tr '[:lower:]' '[:upper:]')\nPPI_PAIR_ID=\"${MASIF_PPI_PAIR_ID:-${PDB_ID}_${CHAIN}}\"\n\ncd /masif/data/masif_site\n\n# 1. Prepare surface + features for the one structure (feed the file directly; skip broken PDB download)\n./data_prepare_one.sh --file \"$INPUT\" \"$PPI_PAIR_ID\"\n\n# 2. Predict per-vertex interaction-site scores with the shipped pretrained weights\n./predict_site.sh \"$PPI_PAIR_ID\"\n\n# 3. Color the surface and (when a true interface is derivable) report ROC-AUC\n./color_site.sh \"$PPI_PAIR_ID\" 2>&1 | tee \"$OUTDIR/color_site.log\" || true\n\n# 4. Collect outputs\nmkdir -p \"$OUTDIR\"\ncp output/all_feat_3l/pred_data/pred_${PPI_PAIR_ID}.npy \"$OUTDIR/\" 2>/dev/null || true\ncp output/all_feat_3l/pred_surfaces/${PPI_PAIR_ID}.ply \"$OUTDIR/\" 2>/dev/null || true\ngrep \"ROC AUC\" \"$OUTDIR/color_site.log\" || true\necho \"MaSIF-site outputs written to $OUTDIR\""


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    argv = [
        "docker", "run", "--rm", "--platform", PLATFORM,
        "-v", f"{inp.parent}:/io/in:ro",
        "-v", f"{out}:/io/out",
        IMAGE, "bash", "-lc", cmd,
    ]
    subprocess.run(argv, check=True)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
