#!/usr/bin/env python3
"""Smoke test for `masif_site`: Prepare 4ZQK chain A, predict site scores, and check ROC-AUC vs true interface is >= 0.80.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "ghcr.io/doctordean/lazarus-masif:site-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /masif/data/masif_site && ./data_prepare_one.sh --file /tmp/4ZQK.pdb 4ZQK_A >/dev/null 2>&1 && ./predict_site.sh 4ZQK_A >/dev/null 2>&1 && ./color_site.sh 4ZQK_A 2>&1 | grep -oE 'ROC AUC score for protein 4ZQK_A : [0-9.]+' | grep -oE '[0-9.]+$' | tail -1 | awk '{print \"roc_auc=\"$1}'"
METRIC = "roc_auc"
THRESHOLD = 0.8


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
