#!/usr/bin/env python3
"""Smoke test for `aizynthfinder_retrosynthesis`: Plan a route for aspirin and assert the target is solved with >=1 fully in-stock route

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/aizynth:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "source activate aizynth && cd /root && printf 'CC(=O)Oc1ccccc1C(=O)O\\n' > /tmp/smiles.txt && aizynthcli --config /root/data/config.yml --smiles /tmp/smiles.txt --output /tmp/out.json.gz >/dev/null 2>&1 && python -c \"import json,gzip; r=json.load(gzip.open('/tmp/out.json.gz','rt'))['data'][0]; print('is_solved=%d' % (1 if (r['is_solved'] is True and r['number_of_solved_routes']>=1) else 0))\""
METRIC = "is_solved"
THRESHOLD = 1


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
