#!/usr/bin/env python3
"""Smoke test for `meirlop_motif_enrichment`: Run enrichment on the shipped DHS scored FASTA with a CTCF-containing motif file and confirm MA0139.1 CTCF auc >= 0.75 with padj < 0.05.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/meirlop:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "source activate meirlop && cd /root/repo && meirlop --jobs 16 --covariates notebooks/covariates.tsv --scan --fa notebooks/scored_fasta.fa notebooks/ctcf_motifs.txt /tmp/smoke_out >/dev/null 2>&1 && python -c \"import pandas as pd; d=pd.read_csv('/tmp/smoke_out/lr_results.tsv',sep='\\t').set_index('motif_id').loc['MA0139.1 CTCF']; assert d.auc>=0.75 and d.padj<0.05, d; print('roc_auc=%.4f'%d.auc)\""
METRIC = "roc_auc"
THRESHOLD = 0.75


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
