"""The integration contract -- the fixed deliverable of a resurrection.

A resurrection isn't "done" when the repo builds; it's done when the buried
capability is callable on a *fresh* input and passes a sanity check the user
defines. The :class:`Contract` captures exactly that, and :func:`emit` turns it
into a self-contained integration package:

    lazarus.yaml     the contract, serialized (human- and machine-readable)
    Dockerfile       FROM the resurrected image, plus the patches Lazarus applied
    predict.py       call the capability on a new input -- no lazarus install needed
    smoke_test.py    prove it: run the sanity check, assert the threshold

The emitted ``predict.py`` shells out to ``docker run`` directly so the package
stands on its own after the week is over.

NOTE: the code templates below are v0 -- the field *schema* is the stable part;
the exact mounts/entrypoint get refined once MaSIF is actually running.
"""

from __future__ import annotations

import json
import string
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

import yaml


@dataclass
class IOSpec:
    """One input or output of the capability."""

    name: str
    type: str          # e.g. "path:pdb", "array:float32", "path:npy"
    description: str = ""


@dataclass
class SmokeCheck:
    """The user-defined proof that the resurrection actually works.

    ``command`` runs inside the container and must produce ``metric`` on stdout
    (as ``<metric>=<value>``); Lazarus asserts it clears ``threshold``.
    """

    description: str
    command: str
    metric: str = "score"
    threshold: float = 0.0
    input_ref: str = ""     # e.g. a benchmark structure id like "4ZQK_A"


@dataclass
class Contract:
    """A callable, verified interface carved out of a dead repo."""

    name: str                       # e.g. "masif_site"
    repo_url: str
    base_image: str                 # the resurrected/snapshotted image tag
    entrypoint: str                 # bash template run in-container; uses $INPUT $OUTDIR
    inputs: list[IOSpec] = field(default_factory=list)
    outputs: list[IOSpec] = field(default_factory=list)
    smoke: Optional[SmokeCheck] = None
    paper: str = ""                 # citation or URL, for provenance
    commit: str = ""                # pinned source commit of the resurrected repo
    patches: list[str] = field(default_factory=list)   # human summary of fixes applied
    platform: str = "linux/amd64"
    gpus: str = ""                  # e.g. "all" for GPU methods (needs nvidia-container-toolkit)

    # -- serialization ---------------------------------------------------
    def to_dict(self) -> dict:
        return asdict(self)

    def to_yaml(self) -> str:
        return yaml.safe_dump(self.to_dict(), sort_keys=False)

    @classmethod
    def from_dict(cls, data: dict) -> "Contract":
        data = dict(data)
        data["inputs"] = [IOSpec(**d) for d in data.get("inputs", [])]
        data["outputs"] = [IOSpec(**d) for d in data.get("outputs", [])]
        smoke = data.get("smoke")
        data["smoke"] = SmokeCheck(**smoke) if smoke else None
        return cls(**data)

    @classmethod
    def from_yaml(cls, text: str) -> "Contract":
        return cls.from_dict(yaml.safe_load(text))


# --------------------------------------------------------------------------
# Templates (string.Template so we don't fight Python/Docker brace syntax)
# --------------------------------------------------------------------------

_DOCKERFILE = string.Template(
    """# Auto-generated by Lazarus for capability: $name
# Source: $repo_url ${commit_line}
FROM $base_image

# Patches Lazarus applied during resurrection:
$patch_comments

WORKDIR /work
"""
)

_PREDICT_PY = string.Template(
    '''#!/usr/bin/env python3
"""Call `$name` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = $base_image
PLATFORM = $platform
GPUS = $gpus  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $$INPUT and $$OUTDIR are substituted at runtime.
ENTRYPOINT = $entrypoint


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$$INPUT", "/io/in/" + inp.name).replace("$$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
'''
)

_SMOKE_PY = string.Template(
    '''#!/usr/bin/env python3
"""Smoke test for `$name`: $smoke_description

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = $base_image
PLATFORM = $platform
GPUS = $gpus  # e.g. "all" to pass GPUs, or None
COMMAND = $smoke_command
METRIC = $smoke_metric
THRESHOLD = $smoke_threshold


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\\s*=\\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''
)


def render_dockerfile(c: Contract) -> str:
    commit_line = f"@ {c.commit}" if c.commit else ""
    patch_comments = "\n".join(f"#   - {p}" for p in c.patches) or "#   (none recorded)"
    return _DOCKERFILE.substitute(
        name=c.name, repo_url=c.repo_url, commit_line=commit_line,
        base_image=c.base_image, patch_comments=patch_comments,
    )


def render_predict_py(c: Contract) -> str:
    # json.dumps -> a properly escaped Python string literal (handles quotes,
    # newlines, backslashes in the entrypoint/image).
    return _PREDICT_PY.substitute(
        name=c.name,
        base_image=json.dumps(c.base_image),
        platform=json.dumps(c.platform),
        entrypoint=json.dumps(c.entrypoint),
        gpus=json.dumps(c.gpus) if c.gpus else "None",
    )


def render_smoke_test(c: Contract) -> str:
    if c.smoke is None:
        raise ValueError(f"contract {c.name!r} has no smoke check to render")
    # Keep the description safe inside the docstring; escape the rest as literals.
    description = c.smoke.description.replace('"""', "'''").replace("\n", " ")
    return _SMOKE_PY.substitute(
        name=c.name,
        base_image=json.dumps(c.base_image),
        platform=json.dumps(c.platform),
        smoke_description=description,
        smoke_command=json.dumps(c.smoke.command),
        smoke_metric=json.dumps(c.smoke.metric),
        smoke_threshold=c.smoke.threshold,
        gpus=json.dumps(c.gpus) if c.gpus else "None",
    )


def emit(contract: Contract, outdir: str | Path) -> Path:
    """Write the full integration package to ``outdir``; return the path."""
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "lazarus.yaml").write_text(contract.to_yaml(), encoding="utf-8")
    (out / "Dockerfile").write_text(render_dockerfile(contract), encoding="utf-8")
    (out / "predict.py").write_text(render_predict_py(contract), encoding="utf-8")
    if contract.smoke is not None:
        (out / "smoke_test.py").write_text(render_smoke_test(contract), encoding="utf-8")
    return out
