#!/usr/bin/env python3
"""Smoke test for `hitea`: Run HiTEA on the bundled test.bam and count TE-annotated candidate insertions

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/hitea:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /usr/local/bin && rm -rf /tmp/smoke && hitea -i examples/test.bam -e MboI -g hg38 -w /tmp/smoke -o test >/dev/null 2>&1 && echo num_candidate_insertions=$(grep -vcE '^#' /tmp/smoke/test.candidate.insertions.bed)"
METRIC = "num_candidate_insertions"
THRESHOLD = 1


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
