#!/usr/bin/env python3
"""Call `coconet_binning` on a fresh input. Auto-generated by Lazarus.

Self-contained: needs only Docker. Works the same against a LOCAL daemon or a
REMOTE one (export DOCKER_HOST=ssh://user@host) — the input and outputs are
copied with `docker cp`, not bind-mounted, so it runs identically on a laptop,
a lab workstation, or a cloud/x86 box.

    python predict.py <input> <output_dir>
"""
import subprocess
import sys
import uuid
from pathlib import Path

IMAGE = "lazarus/coconet:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs (needs nvidia-container-toolkit), or None
# In-container command template; $INPUT and $OUTDIR are substituted at runtime.
ENTRYPOINT = "#!/bin/bash\nset -euo pipefail\n# $INPUT is a directory containing assembly.fasta plus one or more *.bam (with .bai) files.\n# $OUTDIR is where CoCoNet writes its results (bins_*.csv is the headline output).\nmkdir -p \"$OUTDIR\"\ncoconet run \\\n  --fasta \"$INPUT\"/assembly.fasta \\\n  --bam \"$INPUT\"/*.bam \\\n  --output \"$OUTDIR\" \\\n  --threads 1 \\\n  --n-train 64 --n-test 8 --batch-size 2 --min-prevalence 0 \\\n  --test-ratio 0.2 --n-frags 5 \\\n  --compo-neurons 8 4 --cover-neurons 8 4 --cover-kernel 2 --wsize 2 --wstep 2\necho \"Bins written to:\"; ls \"$OUTDIR\"/bins_*.csv"


def _run(*argv, check=True):
    return subprocess.run(list(argv), check=check)


def predict(input_path: str, output_dir: str) -> None:
    inp = Path(input_path).resolve()
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = ENTRYPOINT.replace("$INPUT", "/io/in/" + inp.name).replace("$OUTDIR", "/io/out")
    name = "lazarus-predict-" + uuid.uuid4().hex[:10]
    run_args = ["docker", "run", "-d", "--name", name, "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "sleep", "infinity"]
    _run(*run_args)
    try:
        _run("docker", "exec", name, "mkdir", "-p", "/io/in", "/io/out")
        _run("docker", "cp", str(inp), f"{name}:/io/in/{inp.name}")
        _run("docker", "exec", name, "bash", "-lc", cmd)
        _run("docker", "cp", f"{name}:/io/out/.", str(out))
    finally:
        _run("docker", "rm", "-f", name, check=False)
    print(f"outputs written to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: python predict.py <input> <output_dir>")
    predict(sys.argv[1], sys.argv[2])
