#!/usr/bin/env python3
"""Smoke test for `coconet_binning`: Run coconet on the bundled tests/sim_data (9 viral contigs + 2 BAMs) with smoke-test hyperparameters and count assigned contigs

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/coconet:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /workspace/repo && rm -rf output_test && coconet run --fasta tests/sim_data/assembly.fasta --bam tests/sim_data/*.bam --output output_test --threads 1 --n-train 64 --n-test 8 --batch-size 2 --min-prevalence 0 --test-ratio 0.2 --n-frags 5 --compo-neurons 8 4 --cover-neurons 8 4 --cover-kernel 2 --wsize 2 --wstep 2 >/dev/null 2>&1; echo n_contigs_assigned=$(cat output_test/bins_*.csv | wc -l)"
METRIC = "n_contigs_assigned"
THRESHOLD = 9


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
