#!/usr/bin/env python3
"""Smoke test for `fpocket2`: Run fpocket 2.0 on 4ZQK chain A; expect >=1 detected pocket with a valid druggability score in [0,1] and extractable lining residues.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/fpocket:working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "fpocket_run.sh /opt/fpocket/ref/4ZQK_A.pdb /tmp/smoke"
METRIC = "pockets"
THRESHOLD = 1


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
