#!/usr/bin/env python3
"""Smoke test for `trrosetta_predict`: Run inference on the shipped T1001.a3m example, derive the <8A contact map from the distogram, and compare Pearson correlation against the shipped reference example/T1001.npz; also assert output shapes and that each is a valid probability distribution.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/trrosetta:predict-ready"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && python ./network/predict.py -m ./model2019_07 example/T1001.a3m out.npz >/dev/null 2>&1 && python sanity.py 2>/dev/null | grep pearson_r"
METRIC = "pearson_r"
THRESHOLD = 0.99


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
