#!/usr/bin/env python3
"""Smoke test for `scikit_topt_oc`: Run the OC topology optimizer on the coarsened box cantilever (headless, export_img=False) and assert the recorded compliance drops >=10% while the mean design density holds at the 0.6 volume-fraction target.

Auto-generated by Lazarus. Exits non-zero if the sanity check fails.
"""
import re
import subprocess
import sys

IMAGE = "lazarus/scikit-topt:oc-working"
PLATFORM = "linux/amd64"
GPUS = None  # e.g. "all" to pass GPUs, or None
COMMAND = "cd /root/repo && DST=/tmp/smoke MESH_SIZE=0.4 MAX_ITERS=25 MPLBACKEND=Agg python run_revival.py 2>/dev/null | grep RESULT"
METRIC = "compliance_reduction_ratio"
THRESHOLD = 0.1


def main() -> int:
    run_args = ["docker", "run", "--rm", "--platform", PLATFORM]
    if GPUS:
        run_args += ["--gpus", GPUS]
    run_args += [IMAGE, "bash", "-lc", COMMAND]
    proc = subprocess.run(run_args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    m = re.search(rf"{METRIC}\s*=\s*([0-9.]+)", proc.stdout)
    if not m:
        print(f"FAIL: metric '{METRIC}' not found in output", file=sys.stderr)
        return 1
    value = float(m.group(1))
    ok = value >= THRESHOLD
    print(f"{METRIC}={value} (threshold {THRESHOLD}) -> {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
